export default {
    arrow: 'a',
    bell: 'a',
    bot: 'a',
    bug: 'a',
    close: 'a',
    contribute: 'a',
    copy: 'a',
    exit: 'a',
    feedback: 'a',
    finger_print: 'a',
    ideas: 'a',
    mail: 'a',
    mark: 'a',
    menu: 'a',
    phone: 'a',
    settings: 'a',
    telegram: 'a',
    twitter: 'a',
    user: 'a',
    web: 'a',
    wrench: 'a',
};